spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/studdy}
spring.datasource.username=${DB_USERNAME:studdy}
spring.datasource.password=${DB_PASSWORD:studdy_dev}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
